### PR TITLE
Add .gitignore, remove autocrap

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by debrouxl** [comment]
Looks like there's far more cleanup to be done in this repo than in the tilibs repo :)
I'd like the (small) copy.bat and install.bat files to stay around, i.e.:
* gfm/trunk/glade/copy.bat, gfm/trunk/icons/copy.bat, gfm/trunk/pixmaps/copy.bat, gfm/trunk/po/copy.bat, tilp/trunk/icons/copy.bat, tilp/trunk/po/copy.bat;
* gfm/trunk/install.bat, tilp/trunk/install.bat;
Otherwise, LGTM. Thanks for taking on that task :)

**Comment by uyjulian** [comment]
all right, I put those files back.

**Comment by debrouxl** [comment]
Removing Manpage.txt in gfm breaks the build... i.e. gfm/trunk/man/Makefile.am only worked because the generated file was part of the repo, which may be deemed a bug. Could you fix that Makefile.am, and its sibling in tilp, which is probably better than putting the Manpage.txt file back ? TIA.

**Comment by uyjulian** [comment]
fixed that.

**Comment by debrouxl** [comment]
On the experimental branch, I integrated a modified version of your commits:
* squashed patches #2 and #3, in order not to break bisectability;
* moved the additional .gitignore changes from patch #2 to patch #1;
* fixed the manpage cleaner invocation (yup, it's quite peculiar...), and added -f to rm;
* removed gfm.pot, to match the fact that tilp2.pot was removed.

Builds for me, at least.

Thanks for this PR :)

**Pull request closed without merging**
