### PR TITLE
misc improvements.

### PR DESCRIPTION
**Pull request by adriweb**
cmake: improved various things.

### CODE REVIEW

**Comment by debrouxl** [comment]
I rebased debrouxl:gtk3 onto master, which made a mess of the visible commit history for this PR. That should be fixed by rebasing adriweb:gtk3 onto debrouxl:gtk3 :)

**Comment by adriweb** [comment]
Turns out I did this too yesterday pretty much at the same time, lol.
I'll check and fix things.

**Comment by adriweb** [comment]
2023 update

**Comment by adriweb** [comment]
Rebased again.

**Pull request merged**
